name: EUnit

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    container:
      image: erlang:${{matrix.otp_version}}

    strategy:
      matrix:
        otp_version: ['24.0', '23.3', '22.3', '21.3', '20.3', '19.3']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Compile
      run: rebar3 compile
    - name: Dialyze
      run: rebar3 as test dialyzer
    - name: EUnit tests
      run: TERM=xterm rebar3 eunit
