name: EUnit

on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Test on OTP ${{ matrix.otp_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        otp_version: ['23.2.1', '22.3.4.2', '21.3.8.16', '20.3.8.21', '19.3.6.13']
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2

    - uses: bajankristof/setup-erlang@master
      with:
        otp-version: ${{ matrix.otp_version }}

    - name: Compile
      run: rebar3 compile
    - name: EUnit tests
      run: rebar3 eunit
